### ISSUE TITLE
The script sst_pf.py exits when checking the msr module on CentOS/RHEL

### ISSUE THREAD

**Issue by GaoliangL** [intel/CommsPowerManagement#1]
On Centos/RHEL, the msr module has been built into kernel instead of a separate module. It will return nothing when running 'lsmod | grep msr'. So the script will exit when checking the msr module.
`RET = os.system("lsmod | grep msr >/dev/null")`
`if RET != 0:`
    `print("ERROR: Need the 'msr' kernel module")`
    `print("Please run 'modprobe msr'")`
    `sys.exit(1)`

We saw this issue on CentOS7.6 with Kernel 5.0.9-1.el7.elrepo.x86_64.

**Comment by climberhunt** [comment]
Hi, Thanks for the bug report. I've just pushed a fix, tested it on a system with built-in kernel module, and also did rmmod msr and modprobe msr on a system with 'msr' as a loadable kernel module. Seems OK. Could you check on your CentOS/RHEL systems to be sure it's fixed? Thanks.

**Comment by climberhunt** [comment]
Checked on a system with msr module built into the kernel, as well as on a system with msr module pluggable. Works as expected in tested situations. Closing issue.

**Comment by GaoliangL** [comment]
sst_pf.py with the fix works as expected on our CentOS/RHEL  system, thanks.
