### ISSUE TITLE
Unable to get the PStates using the script

### ISSUE THREAD

**Issue by shivendra1296** [intel/CommsPowerManagement#12]
Hi Team,

We have tried executing the script but are getting the below error:

[root@cmpute CommsPowerManagement-master]# ./power.py

ERROR: No pstate driver file found.
       Are P-States enabled in the system BIOS?

Invalid Driver : []

The Processor details are as follows:

processor       : 79
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6230N CPU @ 2.30GHz
stepping        : 7
microcode       : 0x5003006
cpu MHz         : 2300.000
cache size      : 28160 KB
physical id     : 1
siblings        : 40

Please if you could advise what else do we need to get this working.

Thanks,
Shivendra

**Comment by climberhunt** [comment]
Hi Shivendra,
Are P-States enabled in the system BIOS?
Rgds,
Dave.

**Comment by shivendra1296** [comment]
Hello Dave,

Yes it is enabled. Please see below

[root@cmp ~]# cat /boot/grub2/grub.cfg  | grep "intel_pstate=on"
        linux16 /boot/vmlinuz-3.10.0-1160.25.1.el7.x86_64 root=UUID=fe5bf5b7-6d5c-4cef-9b50-49b297f774da ro console=tty0 console=ttyS0,115200n8 crashkernel=auto rhgb quiet intel_pstate=on  default_hugepagesz=1GB hugepagesz=1G hugepages=326 iommu=pt intel_iommu=on transparent_hugepage=never isolcpus=1-19,21-39,41-59,61-79 $tuned_params
        linux16 /boot/vmlinuz-0-rescue-1d35f654a72d4a2991d8fad4d52107b5 root=UUID=fe5bf5b7-6d5c-4cef-9b50-49b297f774da ro console=tty0 console=ttyS0,115200n8 crashkernel=auto rhgb quiet intel_pstate=on  default_hugepagesz=1GB hugepagesz=1G hugepages=326 iommu=pt intel_iommu=on transparent_hugepage=never isolcpus=1-19,21-39,41-59,61-79

Regrads,
Shivendra

**Comment by climberhunt** [comment]
Hi Shivendra, 
Those are the kernel boot parameters, not the BIOS. Have you checked the BIOS settings? For example, see the "CPU P State Control" screen on the following page: https://dataonsupport.dataonstorage.com/support/solutions/articles/24000067081-bios-configuration-guide

**Comment by climberhunt** [comment]
Hi, I'm assuming the previous comment helped resolve the issue, since that was over a week ago. 
Closing issue.
