### ISSUE TITLE
Why there are only 3 available CPUs ?

### ISSUE THREAD

**Issue by bokidigital** [intel/CommsPowerManagement#7]
https://github.com/intel/CommsPowerManagement/blob/master/sst_bf.py#L192

def get_cpu_name():
    """Get the CPU name from the list of valid SST_BF CPUs"""

    valid_cpus = ["6252N", "6230N", "5218N"]

**Comment by climberhunt** [comment]
Only selected CPUs support this feature. We tested the script on the listed CPUs.

**Comment by yanyh15** [comment]
Why it is N class CPU, not Y class CPU that is for intel speed select?

**Comment by bokidigital** [comment]
> Only selected CPUs support this feature. We tested the script on the listed CPUs.

I think there are more CPU supported Speed Select feature, isn't it?

another question,
If we don't use this script, the CPU frequency will be dynamic ( ex: from 800MHz - 3.1GHz) ? Even BIOS already selects the corresponding SST-BF configuration ( ex: some high priority cores run higher frequency and some low priority cores run lower frequency )

**Comment by climberhunt** [comment]
Hi @yanyh15 ,
> Why it is N class CPU, not Y class CPU that is for intel speed select? https://www.storagereview.com/intel_s_new_speed_select_and_singlesocket_optimized_cpus

There are multiple 'flavours' of Intel SST, including Intel SST-BF (Base Frequency) and SST-PP (Performance Profile). See here for an overview:
https://www.intel.com/content/www/us/en/architecture-and-technology/speed-select-technology-article.html

SST-PP is available on the Y-SKUs and SST-BF is available on the N-SKUs.
