### ISSUE TITLE
power.py line 147  stateList = ""   overwrite the empy list init then cause error

### ISSUE THREAD

**Issue by LiangMa** [intel/CommsPowerManagement#8]
line 147 should be removed

**Comment by climberhunt** [comment]
Need more information. python version, error output, BIOS settings, etc.

**Comment by climberhunt** [comment]
I managed to reproduce. Please add more details in future, which menu option to run, etc. 
Fixed by:
https://github.com/intel/CommsPowerManagement/commit/48d0b0acb0de2bc7471ead8987deafa235fa8669
